# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *" # run at 00:00 AM IST

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - run: echo I've checked out the `${{ matrix.branch }}` branch
  
