# This is a basic workflow to help you get started with Actions

name: Push branch

on:
  workflow_dispatch:
  push:
    branches: [ master, branch-4.0.x ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo I am trigerred from branch
